version: '3'

services:

  # Контейнер с React app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    env_file:
      - .env
    working_dir: /opt/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/opt/client
      - ./static:/opt/static

  # Контейнер с Node.js
  app:
    build:
      context: ./server/app
      dockerfile: Dockerfile
    tty: true
    working_dir: /opt/server
    volumes:
      - ./server/app:/opt/server
      - ./static:/opt/static
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  ws:
    container_name: ws_server
    restart: always
    working_dir: /opt/ws
    build:
      context: server/webSocket
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./server/webSocket:/opt/ws
    ports:
      - "8080:8080"

  # Контейнер с базой данных
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=IROB
      - POSTGRES_NAME=IROB
    restart: always

  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
      - pgadmin
      - client
      - ws
    image: nginx:latest
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    restart: always

  # Контейнер с pgadmin
  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@proglib.io
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    expose:
      - '80'
    restart: always

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug