FROM node:16.10-alpine
RUN apk --no-cache add --virtual .builds-deps build-base python3 tzdata

ENV TZ Europe/Moscow
ENV NODE_PATH /opt/server/node_modules

WORKDIR /opt/server/
COPY ./package.json ./
RUN npm i
COPY . .
CMD [ "npm", "run", "server" ]